name: karebay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  animate_do: ^3.0.2
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.2
  google_generative_ai: ^0.2.2
  flutter_markdown: ^0.6.21
  uuid: ^4.3.3
  provider: ^6.1.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - .env

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf


#derry config
scripts: derry.yaml