// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_2iwxiw2WjJCHIFgdKZ_tpqvks31EfU',
    appId: '1:558196251447:web:07b9a02d03c00839d158b2',
    messagingSenderId: '558196251447',
    projectId: 'karebay-mobile',
    authDomain: 'karebay-mobile.firebaseapp.com',
    storageBucket: 'karebay-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWYNNo_1TdWvXxyzaWBpvHpzbSo7148E',
    appId: '1:558196251447:android:9aa2803f5c72a867d158b2',
    messagingSenderId: '558196251447',
    projectId: 'karebay-mobile',
    storageBucket: 'karebay-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpE-N5nrDKBgjF1dzSJV_5hDstv5d2r7E',
    appId: '1:558196251447:ios:ac456a087dc89f7fd158b2',
    messagingSenderId: '558196251447',
    projectId: 'karebay-mobile',
    storageBucket: 'karebay-mobile.firebasestorage.app',
    iosBundleId: 'com.example.karebay',
  );
}
